### ISSUE TITLE
增加上级代理功能

### ISSUE THREAD

**Issue by QiWei** [zu1k/good-mitm#14]
很多网站需要通过代理访问，没有以发现 good-mitm 可以配置代理的方式。

**Comment by zu1k** [comment]
这个功能可以做，不过最近没空

**Comment by QiWei** [comment]
期待后续版本。
另外问一下 copy-translator 的问题，发现仓库中没有 `deepl-rs = { path = "../../deepl-rs", optional = true }` 这个库，不能编译。
且闪烁的挺利害，是重绘的频率高吗？

**Comment by zu1k** [comment]
@QiWei 不要在这个地方发本项目无关的内容。

并且`copy-translator`是个人自用软件，不提供任何保证，不接收任何issue和pr，如果你认识我可以当面反馈，其余任何方式都不接收
