### ISSUE TITLE
父代理不支持 https

### ISSUE THREAD

**Issue by QiWei** [zu1k/good-mitm#41]
当使用了父代理 `-p http://127.0.0.1:8080 ` ，访问 http 链接可以，https:// 报错。
尝试修改 cargo.toml 里的 hyper-proxy ，加上  `features = ["rustls"]` 也没有效果。

**Comment by BigTear** [comment]
`socks5://` doesn't work too

**Comment by zu1k** [comment]
> https:// 报错

请提供日志

如果是浏览器提示不安全，需要信任证书

**Comment by zu1k** [comment]
> `socks5://` doesn't work too

暂不支持 socks 代理

**Comment by zu1k** [comment]
@QiWei 在 0.3.6 版本中修复了，感谢
