### ISSUE TITLE
Well I am not raising issue. But say thanks!

### ISSUE THREAD

**Issue by muizidn** [zu1k/good-mitm#47]
I found your project from your issues in https://github.com/omjadas/hudsucker. My project requires to implement selective mitm which unfortunately not implemented in hudsucker. But from what I read from good-mitm source code, you already implement it using tunnel mechanism, which surprisingly also solution that I want to implement. Because I am new to Rust and especially TCP level coding, it is very difficult until I found your code.

I just want to say thanks to make it open source and really helps me and hope to the programming community too.

**Comment by muizidn** [comment]
I will just close it as this is not a really issue.

**Comment by zu1k** [comment]
I'm glad this can help you!
