### ISSUE TITLE
应该怎么打印出body呢

### ISSUE THREAD

**Issue by sunianOvO** [zu1k/good-mitm#53]
应该怎么打印出body呢

**Comment by zu1k** [comment]
用js打印即可

**Comment by sunianOvO** [comment]
？在yaml文件中添加js???方便的话可否用教程文档的那个监听所有例子改改

- name: "log"
  filter: all
  action:
    - log-req
    - log-res

**Comment by zu1k** [comment]
https://github.com/zu1k/good-mitm/blob/master/rules/js.yaml
