### ISSUE TITLE
请问为什么Hudsucker里面的example中的ca文件用不了？

### ISSUE THREAD

**Issue by WaylonTian** [zu1k/good-mitm#6]
老哥你好，用你的good-mitm genca得到的两个文件可以正常运行，但是Hudsucker例子里面的两个文件(hudsucker.key 和 hudsucker.pem) 貌似运行就会报错。

我用你的生成 的key和crt文件就能用(good-mitm和hudsucker都可以用），你这里生成的和他例子中的 两个文件有什么不同吗？

先谢过了哈，坐等解答。

**Comment by zu1k** [comment]
https://github.com/est31/rcgen/issues/59#issuecomment-860296585

**Comment by WaylonTian** [comment]
@zu1k  tks
